server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #不注册自己
    fetch-registry: false #不检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

mybatis:
  type-aliases-package: com.peter.bean
  mapper-locations:
    - classpath:mappers/**.xml
spring:
  application:
    name: rubby-eureka
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rubby?useUnicode=true&characterEncoding=utf8&allowMutiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: ENC(yhMP8nSf7QFL6EwKU8c+SQ==)
    password: ENC(k0Q+5ROH+czYJXGrthH9t7iQZaMOCPW2)
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: select 1 from dual
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      filters: stat,wall
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    format:
      date: yyyy-MM-dd
  thymeleaf:
    cache: false

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
jasypt:
  encryptor:
    password: livepassword
logging:
  config: classpath:log4j2.properties