server:
  port: 8011
  tomcat:
    uri-encoding: utf-8
mybatis:
  type-aliases-package: com.peter.bean
  mapper-locations:
    - classpath:mappers/**.xml
spring:
  application:
    name: rubby-cloud-zuul
  messages:
    encoding: UTF-8
logging:
  config: classpath:log4j2.properties
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port} #eureka服务名称
    prefer-ip-address: true
info:
  app.name: Rubby
  company.name: www.rubby.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@
zuul:
  routes: #路由规则
    hadoop:
      service-id: rubby-hadoop
      path: /hadoop/**
  ignored-services: "*" #其他服务不能访问
  prefix: /rubby #url前缀